apiVersion: v1
kind: Pod
metadata:
  name: server-pod
  labels:
    name: server-pod
spec:
  containers:
  - name: server-1
    image: k8s-demo-server
    imagePullPolicy: Never
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080

---

apiVersion: v1
kind: Pod
metadata:
  name: server-pod-1
  labels:
    name: server-pod
spec:
  containers:
  - name: server-1
    image: k8s-demo-server
    imagePullPolicy: Never
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080

---
apiVersion: v1
kind: Pod
metadata:
  name: server-pod-2
  labels:
    name: server-pod
spec:
  containers:
  - name: server-1
    image: k8s-demo-server
    imagePullPolicy: Never
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080